version: '3.1'
services:
  rabbitMQ:
    image: rabbitmq:3.10.5-management
    restart: always
    hostname: rabbitmq
    container_name: rabbitmq-container
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'pass'
    volumes:
      - './data/rabbitmq:/var/lib/rabbitmq'