spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq-params:
  queue-name: javaguides
  routing-key-name: javaguides_routing_key
  queue-name-json: javaguides_json
  routing-key-name-json: javaguides_routing_key_json
  exchange-name: javaguides_exchange